version: 2.1
orbs:
  firecracker: practitest/firecracker@1.0.0
jobs:
  build:
    working_directory: /tmp
    docker:
      - image: clojure:lein-2.8.1
    steps:
      - checkout

      - setup_remote_docker:
          version: 19.03.13

      - run: lein test

      - store_test_results:
          path: test_results

      - store_artifacts:
          path: /tmp/art-1
          destination: artifact-file

      - store_artifacts:
          path: /tmp/artifacts

workflows:
  my-workflow:
    jobs:
      - build:
          context:
            - PT API Token
