version: 2.1
orbs:
  firecracker: practitest/firecracker@1.0.0
jobs:
  build:
    working_directory: ~/circleci.test
    docker:
      - image: clojure:lein-2.8.1
    steps:
      - checkout

      - setup_remote_docker:
          version: 19.03.13

      - run: lein test

      - run: ls

      - run: ls test-results

      - run: ls test

      - store_test_results:
          path: test_results

      - firecracker/fire:
          firecracker_version: v2.0.3
          test_folder: test_results
          author_id: 6604
          api_uri: https://stage.practitest.com/
          api_token: FIRE_API_TOKEN
          email: ${FIRE_EMAIL}
          project_id: 5079
          multitestset: false
          testset_name: rspec

workflows:
  my-workflow:
    jobs:
      - build:
          context:
            - PT API Token
