version: 2.1
orbs:
  firecracker: practitest/firecracker@1.0.0
jobs:
  build:
    docker:
      - image: clojure:lein-2.8.1
    working_directory: ~/circleci.test
    steps:
      - checkout

      - cache-restore:
          # always restore the latest cache
          key: v1-jars-

      - run: lein test

      - cache-save:
          key: v1-jars-{{ checksum "project.clj" }}
          paths:
            - ~/.m2
            -
      - firecracker/fire:
          api_token: FIRE_API_TOKEN
          author_id: '${FIRE_AUTHOR}'
          email: '${FIRE_EMAIL}'
          firecracker_version: v2.0.3
          project_id: '${FIRE_PROJECT_ID}'
          test_folder: test_results
