version: 2.1
orbs:
  firecracker: practitest/firecracker@1.0.0
jobs:
  build:
    docker:
      - image: clojure:lein-2.8.1
    working_directory: ~/circleci.test
    steps:
      - checkout

      - run: lein test

      - firecracker/fire:
          api_token: FIRE_API_TOKEN
          author_id: 123
          email: '${FIRE_EMAIL}'
          firecracker_version: v2.0.3
          project_id: 123
          test_folder: test_results


workflows:
  my-workflow:
    jobs:
      - build:
          context:
            - PT API Token
