version: 2.1
orbs:
  firecracker: practitest/firecracker@1.0.0
jobs:
  build:
    working_directory: ~/circleci.test
    docker:
      - image: clojure:lein-2.8.1
    steps:
      - checkout

      - setup_remote_docker:
          version: 19.03.13

      - run: lein test

      - run: ls
      
      - store_test_results:
          path: test-paths

      - store_artifacts:
          path: test-paths
          destination: artifact-file

      - store_artifacts:
          path: test-paths

workflows:
  my-workflow:
    jobs:
      - build:
          context:
            - PT API Token
