version: 2.1
orbs:
  firecracker: practitest/firecracker@dev:29809f0
jobs:
  build:
    working_directory: ~/circleci.test
    machine:
      image: ubuntu-1604:202007-01
    steps:
      - checkout

      - run: lein test

      - store_test_results:
          path: test-results

      - store_artifacts:
          path: test-results

      - firecracker/fire:
          project_id: ${FIRE_PROJECT_ID}
          author_id: ${FIRE_AUTHOR}
          api_token: FIRE_API_TOKEN
          email: ${FIRE_EMAIL}
          firecracker_version: v2.0.3
          test_folder: test-results
          testset_name: Circleci_Testset

workflows:
  my-workflow:
    jobs:
      - build:
          context:
            - PT API Token
